# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - pagopa-github-bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
        -
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixing 🔥
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
