version: '3.8'

services:
  app:
    container_name: 'pagopa-gpd-payments-pull'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile_integration_test
      context: ../
      args:
        QUARKUS_PROFILE: prod
        APP_NAME: pagopa-gpd-payments-pull
        SLEEP_FOR_INTEGRATION: 180000
    env_file:
      - ./.env
    ports:
      - "8080:8080"

volumes:
  prometheus_data: { }
  grafana_data: { }
networks:
  infra:
    driver: bridge
